[package]
name = "zmq_rust"
version = "0.1.0"
authors = ["Jay Thomason <jay@covariant.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.3.3"
zmq = "0.9.2"
